### PR TITLE
feat: add mqtt for RPi

### LINKED ISSUE #1: ESPHome/ESP32 version
Hi,

first of all, wonderful project, thanks for taking the time and effort to look into this device.
I will try to set it up to test it out on my spare RPi device.

However, because the project is written specifically with the pyRF24 library, I probably won't be able to use it on my installation of Home Assistant, which is virtualized on a x86 device. 

I was looking into using a serial converter like a CH341 to be able to interface with an NRF24 on a non-RPi device, however, I realised that probably the most convinient solution would be to use a device such as ESP32 with the ESPHome project.

Alternatively, maybe you could add MQTT to the current project, so one could have a spare RPi as "gateway"? 

What are your thoughts on this? 

Thanks!

### PR DESCRIPTION
**Pull request by ersonp**
Fixes: #1

### CODE REVIEW

**Comment by frostworx** [comment]
Thank you both @lamperez for the project itself and @ersonp for the pull request!

To be honest I'm undecided yet, if I want to activate a stray Pi for the light bar _(I'd love to see a #1  as well :))_, but great to see some active development for the MJGJD01YL devices.

**Comment by frostworx** [comment]
Sorry for the noise.

I can confirm that the xiaomi-lightbar-nrf24 mqtt light bar integration into home assistant works excellent _(running on a pi4b)_

Would be great if the PR would be merged!

`pip install paho-mqtt`

should be added to the readme then.

Thank you very much!

**Comment by lamperez** [comment]
Thank you for the great work with the integration.

**Comment by nervous-inhuman** [comment]
> Thank you for the great work with the integration.

I'd like to second this, thank you for the change! :)

**Pull request merged**
